language: node_js

node_js:
  - 'stable'

cache:
  directories:
    - node_modules
    - dist
jobs:
  include:
    - stage: build
      before_install:
        - BUILD_DIR=`pwd`
        - git clone https://github.com/VisualStorytelling/provenance-slide-deck.git ../provenance-slide-deck
        - cd ../provenance-slide-deck
        - yarn install
        - yarn build
        - cd $BUILD_DIR
      install: yarn
      script:
        - rm -rf dist
        - yarn build
    - stage: deploy to GH pages
      if: (branch = master)
      install: true
      script:
        - pwd
        - openssl aes-256-cbc -K $encrypted_91204e326c85_key -iv $encrypted_91204e326c85_iv -in github_deploy_key.enc -out ~/.ssh/id_rsa -d
        - chmod 400 ~/.ssh/id_rsa
        - git clone -b gh-pages --single-branch git@github.com:VisualStorytelling/brainvis.git gh-pages
        - cp -r ./dist/brainvis/* ./gh-pages/
        - cd gh-pages
        - git add .
        - git commit -m "travis deploy"
        - git push
